// (C) 1992-2018 Intel Corporation.                            
// Intel, the Intel logo, Intel, MegaCore, NIOS II, Quartus and TalkBack words    
// and logos are trademarks of Intel Corporation or its subsidiaries in the U.S.  
// and/or other countries. Other marks and brands may be claimed as the property  
// of others. See Trademarks on intel.com for full list of Intel trademarks or    
// the Trademarks & Brands Names Database (if Intel) or See www.Intel.com/legal (if Altera) 
// Your use of Intel Corporation's design tools, logic functions and other        
// software and tools, and its AMPP partner logic functions, and any output       
// files any of the foregoing (including device programming or simulation         
// files), and any associated documentation or information are expressly subject  
// to the terms and conditions of the Altera Program License Subscription         
// Agreement, Intel MegaCore Function License Agreement, or other applicable      
// license agreement, including, without limitation, that your use is for the     
// sole purpose of programming logic devices manufactured by Intel and sold by    
// Intel or its authorized distributors.  Please refer to the applicable          
// agreement for further details.                                                 

// Generated by Intel(R) HLS Compiler, Version 18.1.0 Build 625

/////////////////////////////////////////////////////////////////
// MODULE gmm_substract_internal
/////////////////////////////////////////////////////////////////
module gmm_substract_internal
(
   input logic clock,
   input logic resetn,
   // AVST snk
   input logic snk_valid,
   output logic snk_ready,
   input logic [175:0] snk_data,
   // AVST src
   output logic src_valid,
   input logic src_ready,
   output logic [175:0] src_data,
   input logic [7:0] d,
   input logic [7:0] bg_th,
   input logic [9:0] in_alpha,
   input logic [7:0] s
);
   // INST gmm_substract_internal of gmm_substract_function_wrapper
   gmm_substract_function_wrapper gmm_substract_internal
   (
      .clock(clock),
      .resetn(resetn),
      // AVST avst_iord_bl_snk
      .avst_iord_bl_snk_valid(snk_valid),
      .avst_iord_bl_snk_ready(snk_ready),
      .avst_iord_bl_snk_data(snk_data),
      // AVST avst_iowr_bl_src
      .avst_iowr_bl_src_valid(src_valid),
      .avst_iowr_bl_src_ready(src_ready),
      .avst_iowr_bl_src_data(src_data),
      .d(d),
      .bg_th(bg_th),
      .in_alpha(in_alpha),
      .s(s)
   );

endmodule

