# TCL File Generated by Component Editor 18.1
# Fri Nov 15 09:41:58 GMT+03:00 2019
# DO NOT MODIFY


# 
# gmm_fg_detector "GMM Foreground Arbiter" v1.13
# KalshchikovAA@gmail.com 2019.11.15.09:41:58
# This module receives video sequence from camera and processes one by GaussianMixtureModel (GMM) algorithm to determine which pixel is foregroung (FG) or background (BG).
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module gmm_fg_detector
# 
set_module_property DESCRIPTION "This module receives video sequence from camera and processes one by GaussianMixtureModel (GMM) algorithm to determine which pixel is foregroung (FG) or background (BG)."
set_module_property NAME gmm_fg_detector
set_module_property VERSION 1.13
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR KalshchikovAA@gmail.com
set_module_property DISPLAY_NAME "GMM Foreground Arbiter"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL gmm_fg_detector
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file altera_avalon_sc_fifo.v VERILOG PATH hw/altera_avalon_sc_fifo.v
add_fileset_file gmm_fg_detector.sv SYSTEM_VERILOG PATH hw/gmm_fg_detector.sv TOP_LEVEL_FILE
add_fileset_file gmm_substract_internal.v SYSTEM_VERILOG PATH gmm_substract_internal.v
add_fileset_file gmm_dma_control.sv SYSTEM_VERILOG PATH hw/gmm_dma_control.sv

# GMM
add_fileset_file gmm_structures.svh SYSTEM_VERILOG_INCLUDE PATH gmm_substract/gmm_structures.svh
add_fileset_file backpressure_machine.sv SYSTEM_VERILOG PATH gmm_substract/backpressure_machine.sv
# GMM additional
add_fileset_file gmm_subtract.sv SYSTEM_VERILOG PATH gmm_substract/gmm_subtract.sv
add_fileset_file gmm_subtract_B_calc_pipe.sv SYSTEM_VERILOG PATH gmm_substract/gmm_subtract_B_calc_pipe.sv
add_fileset_file gmm_subtract_color_pipe.sv SYSTEM_VERILOG PATH gmm_substract/gmm_subtract_color_pipe.sv
add_fileset_file gmm_subtract_fg_detector_pipe.sv SYSTEM_VERILOG PATH gmm_substract/gmm_subtract_fg_detector_pipe.sv
add_fileset_file gmm_subtract_fp_probability_pipe.sv SYSTEM_VERILOG PATH gmm_substract/gmm_subtract_fp_probability_pipe.sv
add_fileset_file gmm_subtract_params_update_pipe.sv SYSTEM_VERILOG PATH gmm_substract/gmm_subtract_params_update_pipe.sv
add_fileset_file gmm_subtract_sort_pipe.sv SYSTEM_VERILOG PATH gmm_substract/gmm_subtract_sort_pipe.sv
add_fileset_file gmm_subtract_vars_pipe.sv SYSTEM_VERILOG PATH gmm_substract/gmm_subtract_vars_pipe.sv
add_fileset_file gmm_subtract_w_normalized_pipe.sv SYSTEM_VERILOG PATH gmm_substract/gmm_subtract_w_normalized_pipe.sv

# FP_COMP
add_fileset_file fp_comp_base.v VERILOG PATH gmm_substract/FP_COMP/fp_comp_base.v
add_fileset_file fp_comp_wrap.sv SYSTEM_VERILOG PATH gmm_substract/FP_COMP/fp_comp_wrap.sv

# FP_DIV
add_fileset_file fp_div_base.v VERILOG PATH gmm_substract/FP_DIV/fp_div_base.v
add_fileset_file fp_div_wrap.sv SYSTEM_VERILOG PATH gmm_substract/FP_DIV/fp_div_wrap.sv
add_fileset_file fp_div_base.hex HEX PATH gmm_substract/FP_DIV/fp_div_base.hex
add_fileset_file fp_div_base.ver OTHER PATH gmm_substract/FP_DIV/fp_div_base.ver

# FP_EXP
add_fileset_file fp_exp_base.v VERILOG PATH gmm_substract/FP_EXP/fp_exp_base.v
add_fileset_file fp_exp_wrap.sv SYSTEM_VERILOG PATH gmm_substract/FP_EXP/fp_exp_wrap.sv

# FP_MUL
add_fileset_file fp_mul_base.v VERILOG PATH gmm_substract/FP_MUL/fp_mul_base.v
add_fileset_file fp_mul_wrap.sv SYSTEM_VERILOG PATH gmm_substract/FP_MUL/fp_mul_wrap.sv

# INT_CONVERT_TO_FP
add_fileset_file int_convert_to_fp_base.v VERILOG PATH gmm_substract/INT_CONVERT_TO_FP/int_convert_to_fp_base.v
add_fileset_file int_convert_to_fp_wrap.sv SYSTEM_VERILOG PATH gmm_substract/INT_CONVERT_TO_FP/int_convert_to_fp_wrap.sv

# LMP_SQRT
add_fileset_file lpm_sqrt.v VERILOG PATH gmm_substract/LMP_SQRT/lpm_sqrt.v
add_fileset_file lpm_sqrt_wrap.sv SYSTEM_VERILOG PATH gmm_substract/LMP_SQRT/lpm_sqrt_wrap.sv

# LPM_DIV
add_fileset_file lpm_div.v VERILOG PATH gmm_substract/LPM_DIV/lpm_div.v
add_fileset_file lpm_div_wrap.sv SYSTEM_VERILOG PATH gmm_substract/LPM_DIV/lpm_div_wrap.sv

# LPM_DIV32
add_fileset_file lpm_div32.v VERILOG PATH gmm_substract/LPM_DIV32/lpm_div32.v
add_fileset_file lpm_div32_wrap.sv SYSTEM_VERILOG PATH gmm_substract/LPM_DIV32/lpm_div32_wrap.sv

# 
# parameters
# 
add_parameter FRAMES_NUM INTEGER 2
set_parameter_property FRAMES_NUM DEFAULT_VALUE 2
set_parameter_property FRAMES_NUM DISPLAY_NAME FRAMES_NUM
set_parameter_property FRAMES_NUM TYPE INTEGER
set_parameter_property FRAMES_NUM UNITS None
set_parameter_property FRAMES_NUM ALLOWED_RANGES -2147483648:2147483647
set_parameter_property FRAMES_NUM HDL_PARAMETER true
add_parameter VIDEO_START_ADDR INTEGER 0
set_parameter_property VIDEO_START_ADDR DEFAULT_VALUE 0
set_parameter_property VIDEO_START_ADDR DISPLAY_NAME VIDEO_START_ADDR
set_parameter_property VIDEO_START_ADDR TYPE INTEGER
set_parameter_property VIDEO_START_ADDR UNITS None
set_parameter_property VIDEO_START_ADDR ALLOWED_RANGES -2147483648:2147483647
set_parameter_property VIDEO_START_ADDR HDL_PARAMETER true
add_parameter VIDEO_SPAN_BYTES INTEGER 33177600
set_parameter_property VIDEO_SPAN_BYTES DEFAULT_VALUE 33177600
set_parameter_property VIDEO_SPAN_BYTES DISPLAY_NAME VIDEO_SPAN_BYTES
set_parameter_property VIDEO_SPAN_BYTES TYPE INTEGER
set_parameter_property VIDEO_SPAN_BYTES UNITS None
set_parameter_property VIDEO_SPAN_BYTES ALLOWED_RANGES -2147483648:2147483647
set_parameter_property VIDEO_SPAN_BYTES HDL_PARAMETER true
add_parameter CONTROL_SPAN_BYTES INTEGER 32
set_parameter_property CONTROL_SPAN_BYTES DEFAULT_VALUE 32
set_parameter_property CONTROL_SPAN_BYTES DISPLAY_NAME CONTROL_SPAN_BYTES
set_parameter_property CONTROL_SPAN_BYTES TYPE INTEGER
set_parameter_property CONTROL_SPAN_BYTES UNITS None
set_parameter_property CONTROL_SPAN_BYTES ALLOWED_RANGES -2147483648:2147483647
set_parameter_property CONTROL_SPAN_BYTES HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point cpu
# 
add_interface cpu avalon end
set_interface_property cpu addressUnits WORDS
set_interface_property cpu associatedClock clock
set_interface_property cpu associatedReset rst
set_interface_property cpu bitsPerSymbol 8
set_interface_property cpu burstOnBurstBoundariesOnly false
set_interface_property cpu burstcountUnits WORDS
set_interface_property cpu explicitAddressSpan 0
set_interface_property cpu holdTime 0
set_interface_property cpu linewrapBursts false
set_interface_property cpu maximumPendingReadTransactions 0
set_interface_property cpu maximumPendingWriteTransactions 0
set_interface_property cpu readLatency 0
set_interface_property cpu readWaitStates 0
set_interface_property cpu readWaitTime 0
set_interface_property cpu setupTime 0
set_interface_property cpu timingUnits Cycles
set_interface_property cpu writeWaitTime 0
set_interface_property cpu ENABLED true
set_interface_property cpu EXPORT_OF ""
set_interface_property cpu PORT_NAME_MAP ""
set_interface_property cpu CMSIS_SVD_VARIABLES ""
set_interface_property cpu SVD_ADDRESS_GROUP ""

add_interface_port cpu cpu_write write Input 1
add_interface_port cpu cpu_read read Input 1
add_interface_port cpu cpu_writedata writedata Input 32
add_interface_port cpu cpu_readdata readdata Output 32
add_interface_port cpu cpu_addr address Input 4
add_interface_port cpu cpu_cs chipselect Input 1
set_interface_assignment cpu embeddedsw.configuration.isFlash 0
set_interface_assignment cpu embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment cpu embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment cpu embeddedsw.configuration.isPrintableDevice 0


# 
# connection point snk_video
# 
add_interface snk_video avalon_streaming end
set_interface_property snk_video associatedClock clock
set_interface_property snk_video associatedReset rst
set_interface_property snk_video dataBitsPerSymbol 8
set_interface_property snk_video errorDescriptor ""
set_interface_property snk_video firstSymbolInHighOrderBits true
set_interface_property snk_video maxChannel 0
set_interface_property snk_video readyLatency 0
set_interface_property snk_video ENABLED true
set_interface_property snk_video EXPORT_OF ""
set_interface_property snk_video PORT_NAME_MAP ""
set_interface_property snk_video CMSIS_SVD_VARIABLES ""
set_interface_property snk_video SVD_ADDRESS_GROUP ""

add_interface_port snk_video snk_video_data data Input 24
add_interface_port snk_video snk_video_eop endofpacket Input 1
add_interface_port snk_video snk_video_ready ready Output 1
add_interface_port snk_video snk_video_sop startofpacket Input 1
add_interface_port snk_video snk_video_valid valid Input 1


# 
# connection point snk_mem
# 
add_interface snk_mem avalon_streaming end
set_interface_property snk_mem associatedClock clock
set_interface_property snk_mem associatedReset rst
set_interface_property snk_mem dataBitsPerSymbol 8
set_interface_property snk_mem errorDescriptor ""
set_interface_property snk_mem firstSymbolInHighOrderBits true
set_interface_property snk_mem maxChannel 0
set_interface_property snk_mem readyLatency 0
set_interface_property snk_mem ENABLED true
set_interface_property snk_mem EXPORT_OF ""
set_interface_property snk_mem PORT_NAME_MAP ""
set_interface_property snk_mem CMSIS_SVD_VARIABLES ""
set_interface_property snk_mem SVD_ADDRESS_GROUP ""

add_interface_port snk_mem snk_mem_data data Input 128
add_interface_port snk_mem snk_mem_empty empty Input 4
add_interface_port snk_mem snk_mem_eop endofpacket Input 1
add_interface_port snk_mem snk_mem_ready ready Output 1
add_interface_port snk_mem snk_mem_sop startofpacket Input 1
add_interface_port snk_mem snk_mem_valid valid Input 1


# 
# connection point src_video
# 
add_interface src_video avalon_streaming start
set_interface_property src_video associatedClock clock
set_interface_property src_video associatedReset rst
set_interface_property src_video dataBitsPerSymbol 49
set_interface_property src_video errorDescriptor ""
set_interface_property src_video firstSymbolInHighOrderBits true
set_interface_property src_video maxChannel 0
set_interface_property src_video readyLatency 0
set_interface_property src_video ENABLED true
set_interface_property src_video EXPORT_OF ""
set_interface_property src_video PORT_NAME_MAP ""
set_interface_property src_video CMSIS_SVD_VARIABLES ""
set_interface_property src_video SVD_ADDRESS_GROUP ""

add_interface_port src_video src_video_data data Output 49
add_interface_port src_video src_video_eop endofpacket Output 1
add_interface_port src_video src_video_ready ready Input 1
add_interface_port src_video src_video_sop startofpacket Output 1
add_interface_port src_video src_video_valid valid Output 1


# 
# connection point src_mem
# 
add_interface src_mem avalon_streaming start
set_interface_property src_mem associatedClock clock
set_interface_property src_mem associatedReset rst
set_interface_property src_mem dataBitsPerSymbol 8
set_interface_property src_mem errorDescriptor ""
set_interface_property src_mem firstSymbolInHighOrderBits true
set_interface_property src_mem maxChannel 0
set_interface_property src_mem readyLatency 0
set_interface_property src_mem ENABLED true
set_interface_property src_mem EXPORT_OF ""
set_interface_property src_mem PORT_NAME_MAP ""
set_interface_property src_mem CMSIS_SVD_VARIABLES ""
set_interface_property src_mem SVD_ADDRESS_GROUP ""

add_interface_port src_mem src_mem_data data Output 128
add_interface_port src_mem src_mem_empty empty Output 4
add_interface_port src_mem src_mem_eop endofpacket Output 1
add_interface_port src_mem src_mem_ready ready Input 1
add_interface_port src_mem src_mem_sop startofpacket Output 1
add_interface_port src_mem src_mem_valid valid Output 1


# 
# connection point rst
# 
add_interface rst reset end
set_interface_property rst associatedClock clock
set_interface_property rst synchronousEdges DEASSERT
set_interface_property rst ENABLED true
set_interface_property rst EXPORT_OF ""
set_interface_property rst PORT_NAME_MAP ""
set_interface_property rst CMSIS_SVD_VARIABLES ""
set_interface_property rst SVD_ADDRESS_GROUP ""

add_interface_port rst rst reset Input 1


# 
# connection point in_ram
# 
add_interface in_ram avalon start
set_interface_property in_ram addressUnits WORDS
set_interface_property in_ram associatedClock clock
set_interface_property in_ram associatedReset rst
set_interface_property in_ram bitsPerSymbol 8
set_interface_property in_ram burstOnBurstBoundariesOnly false
set_interface_property in_ram burstcountUnits WORDS
set_interface_property in_ram doStreamReads false
set_interface_property in_ram doStreamWrites false
set_interface_property in_ram holdTime 0
set_interface_property in_ram linewrapBursts false
set_interface_property in_ram maximumPendingReadTransactions 0
set_interface_property in_ram maximumPendingWriteTransactions 0
set_interface_property in_ram readLatency 1
set_interface_property in_ram readWaitTime 0
set_interface_property in_ram setupTime 0
set_interface_property in_ram timingUnits Cycles
set_interface_property in_ram writeWaitTime 0
set_interface_property in_ram ENABLED true
set_interface_property in_ram EXPORT_OF ""
set_interface_property in_ram PORT_NAME_MAP ""
set_interface_property in_ram CMSIS_SVD_VARIABLES ""
set_interface_property in_ram SVD_ADDRESS_GROUP ""

add_interface_port in_ram in_ram_addr address Output 6
add_interface_port in_ram in_ram_write write Output 1
add_interface_port in_ram in_ram_writedata writedata Output 256
add_interface_port in_ram in_ram_read read Output 1
add_interface_port in_ram in_ram_readdata readdata Input 256


# 
# connection point out_ram
# 
add_interface out_ram avalon start
set_interface_property out_ram addressUnits WORDS
set_interface_property out_ram associatedClock clock
set_interface_property out_ram associatedReset rst
set_interface_property out_ram bitsPerSymbol 8
set_interface_property out_ram burstOnBurstBoundariesOnly false
set_interface_property out_ram burstcountUnits WORDS
set_interface_property out_ram doStreamReads false
set_interface_property out_ram doStreamWrites false
set_interface_property out_ram holdTime 0
set_interface_property out_ram linewrapBursts false
set_interface_property out_ram maximumPendingReadTransactions 0
set_interface_property out_ram maximumPendingWriteTransactions 0
set_interface_property out_ram readLatency 1
set_interface_property out_ram readWaitTime 0
set_interface_property out_ram setupTime 0
set_interface_property out_ram timingUnits Cycles
set_interface_property out_ram writeWaitTime 0
set_interface_property out_ram ENABLED true
set_interface_property out_ram EXPORT_OF ""
set_interface_property out_ram PORT_NAME_MAP ""
set_interface_property out_ram CMSIS_SVD_VARIABLES ""
set_interface_property out_ram SVD_ADDRESS_GROUP ""

add_interface_port out_ram out_ram_addr address Output 6
add_interface_port out_ram out_ram_write write Output 1
add_interface_port out_ram out_ram_writedata writedata Output 256
add_interface_port out_ram out_ram_read read Output 1
add_interface_port out_ram out_ram_readdata readdata Input 256


# 
# connection point in_pref
# 
add_interface in_pref avalon start
set_interface_property in_pref addressUnits WORDS
set_interface_property in_pref associatedClock clock
set_interface_property in_pref associatedReset rst
set_interface_property in_pref bitsPerSymbol 8
set_interface_property in_pref burstOnBurstBoundariesOnly false
set_interface_property in_pref burstcountUnits WORDS
set_interface_property in_pref doStreamReads false
set_interface_property in_pref doStreamWrites false
set_interface_property in_pref holdTime 0
set_interface_property in_pref linewrapBursts false
set_interface_property in_pref maximumPendingReadTransactions 0
set_interface_property in_pref maximumPendingWriteTransactions 0
set_interface_property in_pref readLatency 1
set_interface_property in_pref readWaitTime 0
set_interface_property in_pref setupTime 0
set_interface_property in_pref timingUnits Cycles
set_interface_property in_pref writeWaitTime 0
set_interface_property in_pref ENABLED true
set_interface_property in_pref EXPORT_OF ""
set_interface_property in_pref PORT_NAME_MAP ""
set_interface_property in_pref CMSIS_SVD_VARIABLES ""
set_interface_property in_pref SVD_ADDRESS_GROUP ""

add_interface_port in_pref in_pref_addr address Output 3
add_interface_port in_pref in_pref_write write Output 1
add_interface_port in_pref in_pref_writedata writedata Output 32
add_interface_port in_pref in_pref_read read Output 1
add_interface_port in_pref in_pref_readdata readdata Input 32


# 
# connection point out_pref
# 
add_interface out_pref avalon start
set_interface_property out_pref addressUnits WORDS
set_interface_property out_pref associatedClock clock
set_interface_property out_pref associatedReset rst
set_interface_property out_pref bitsPerSymbol 8
set_interface_property out_pref burstOnBurstBoundariesOnly false
set_interface_property out_pref burstcountUnits WORDS
set_interface_property out_pref doStreamReads false
set_interface_property out_pref doStreamWrites false
set_interface_property out_pref holdTime 0
set_interface_property out_pref linewrapBursts false
set_interface_property out_pref maximumPendingReadTransactions 0
set_interface_property out_pref maximumPendingWriteTransactions 0
set_interface_property out_pref readLatency 1
set_interface_property out_pref readWaitTime 0
set_interface_property out_pref setupTime 0
set_interface_property out_pref timingUnits Cycles
set_interface_property out_pref writeWaitTime 0
set_interface_property out_pref ENABLED true
set_interface_property out_pref EXPORT_OF ""
set_interface_property out_pref PORT_NAME_MAP ""
set_interface_property out_pref CMSIS_SVD_VARIABLES ""
set_interface_property out_pref SVD_ADDRESS_GROUP ""

add_interface_port out_pref out_pref_addr address Output 3
add_interface_port out_pref out_pref_write write Output 1
add_interface_port out_pref out_pref_writedata writedata Output 32
add_interface_port out_pref out_pref_read read Output 1
add_interface_port out_pref out_pref_readdata readdata Input 32

