// (C) 1992-2018 Intel Corporation.                            
// Intel, the Intel logo, Intel, MegaCore, NIOS II, Quartus and TalkBack words    
// and logos are trademarks of Intel Corporation or its subsidiaries in the U.S.  
// and/or other countries. Other marks and brands may be claimed as the property  
// of others. See Trademarks on intel.com for full list of Intel trademarks or    
// the Trademarks & Brands Names Database (if Intel) or See www.Intel.com/legal (if Altera) 
// Your use of Intel Corporation's design tools, logic functions and other        
// software and tools, and its AMPP partner logic functions, and any output       
// files any of the foregoing (including device programming or simulation         
// files), and any associated documentation or information are expressly subject  
// to the terms and conditions of the Altera Program License Subscription         
// Agreement, Intel MegaCore Function License Agreement, or other applicable      
// license agreement, including, without limitation, that your use is for the     
// sole purpose of programming logic devices manufactured by Intel and sold by    
// Intel or its authorized distributors.  Please refer to the applicable          
// agreement for further details.                                                 

// Generated by Intel(R) HLS Compiler, Version 18.1.0 Build 625

typedef struct packed {
 logic [7:0] inherited_class;
} class_ac_int_4;



typedef struct packed {
 logic [7:0] inherited_class;
} class_ac_int_7;



typedef struct packed {
 class_ac_int [2:0]  color;
} struct_rgb_t;



typedef struct packed {
 logic [7:0] inherited_class;
} class_ac_int_10;



typedef struct packed {
 class_ac_int_10  is_fg;
 struct_rgb_t  rgb_new;
 struct_cluster_t [2:0]  cluster;
 class_ac_int_7  u;
 class_ac_int_7  chm;
 class_ac_int_4  clusters_num;
} struct_data_t;



