# TCL File Generated by Component Editor 18.1
# Fri Nov 15 09:09:44 GMT+03:00 2019
# DO NOT MODIFY


# 
# snk_video_adapter "Avalon-ST Sink Video Adapter" v1.0
# KalshchikovAA@gmail.com 2019.11.15.09:09:44
# it ignores empty signal from the sink
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module snk_video_adapter
# 
set_module_property DESCRIPTION "it ignores empty signal from the sink"
set_module_property NAME snk_video_adapter
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR KalshchikovAA@gmail.com
set_module_property DISPLAY_NAME "Avalon-ST Sink Video Adapter"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL snk_video_adapter
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file snk_video_adapter.sv SYSTEM_VERILOG PATH snk_video_adapter.sv TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point snk
# 
add_interface snk avalon_streaming end
set_interface_property snk associatedClock clk
set_interface_property snk associatedReset rst
set_interface_property snk dataBitsPerSymbol 8
set_interface_property snk errorDescriptor ""
set_interface_property snk firstSymbolInHighOrderBits true
set_interface_property snk maxChannel 0
set_interface_property snk readyLatency 0
set_interface_property snk ENABLED true
set_interface_property snk EXPORT_OF ""
set_interface_property snk PORT_NAME_MAP ""
set_interface_property snk CMSIS_SVD_VARIABLES ""
set_interface_property snk SVD_ADDRESS_GROUP ""

add_interface_port snk snk_data data Input 24
add_interface_port snk snk_empty empty Input 2
add_interface_port snk snk_eop endofpacket Input 1
add_interface_port snk snk_ready ready Output 1
add_interface_port snk snk_sop startofpacket Input 1
add_interface_port snk snk_valid valid Input 1


# 
# connection point src
# 
add_interface src avalon_streaming start
set_interface_property src associatedClock clk
set_interface_property src associatedReset rst
set_interface_property src dataBitsPerSymbol 8
set_interface_property src errorDescriptor ""
set_interface_property src firstSymbolInHighOrderBits true
set_interface_property src maxChannel 0
set_interface_property src readyLatency 0
set_interface_property src ENABLED true
set_interface_property src EXPORT_OF ""
set_interface_property src PORT_NAME_MAP ""
set_interface_property src CMSIS_SVD_VARIABLES ""
set_interface_property src SVD_ADDRESS_GROUP ""

add_interface_port src src_data data Output 24
add_interface_port src src_eop endofpacket Output 1
add_interface_port src src_ready ready Input 1
add_interface_port src src_sop startofpacket Output 1
add_interface_port src src_valid valid Output 1


# 
# connection point clk
# 
add_interface clk clock end
set_interface_property clk clockRate 0
set_interface_property clk ENABLED true
set_interface_property clk EXPORT_OF ""
set_interface_property clk PORT_NAME_MAP ""
set_interface_property clk CMSIS_SVD_VARIABLES ""
set_interface_property clk SVD_ADDRESS_GROUP ""

add_interface_port clk clk clk Input 1


# 
# connection point rst
# 
add_interface rst reset end
set_interface_property rst associatedClock clk
set_interface_property rst synchronousEdges DEASSERT
set_interface_property rst ENABLED true
set_interface_property rst EXPORT_OF ""
set_interface_property rst PORT_NAME_MAP ""
set_interface_property rst CMSIS_SVD_VARIABLES ""
set_interface_property rst SVD_ADDRESS_GROUP ""

add_interface_port rst rst reset Input 1

