	soc_system u0 (
		.alt_vip_itc_0_clocked_video_vid_clk        (<connected-to-alt_vip_itc_0_clocked_video_vid_clk>),        //  alt_vip_itc_0_clocked_video.vid_clk
		.alt_vip_itc_0_clocked_video_vid_data       (<connected-to-alt_vip_itc_0_clocked_video_vid_data>),       //                             .vid_data
		.alt_vip_itc_0_clocked_video_underflow      (<connected-to-alt_vip_itc_0_clocked_video_underflow>),      //                             .underflow
		.alt_vip_itc_0_clocked_video_vid_datavalid  (<connected-to-alt_vip_itc_0_clocked_video_vid_datavalid>),  //                             .vid_datavalid
		.alt_vip_itc_0_clocked_video_vid_v_sync     (<connected-to-alt_vip_itc_0_clocked_video_vid_v_sync>),     //                             .vid_v_sync
		.alt_vip_itc_0_clocked_video_vid_h_sync     (<connected-to-alt_vip_itc_0_clocked_video_vid_h_sync>),     //                             .vid_h_sync
		.alt_vip_itc_0_clocked_video_vid_f          (<connected-to-alt_vip_itc_0_clocked_video_vid_f>),          //                             .vid_f
		.alt_vip_itc_0_clocked_video_vid_h          (<connected-to-alt_vip_itc_0_clocked_video_vid_h>),          //                             .vid_h
		.alt_vip_itc_0_clocked_video_vid_v          (<connected-to-alt_vip_itc_0_clocked_video_vid_v>),          //                             .vid_v
		.clk_clk                                    (<connected-to-clk_clk>),                                    //                          clk.clk
		.clk_d8m_clk                                (<connected-to-clk_d8m_clk>),                                //                      clk_d8m.clk
		.clk_hdmi_clk                               (<connected-to-clk_hdmi_clk>),                               //                     clk_hdmi.clk
		.clk_hdmi_ref_clk                           (<connected-to-clk_hdmi_ref_clk>),                           //                 clk_hdmi_ref.clk
		.clk_hps_ref_clk                            (<connected-to-clk_hps_ref_clk>),                            //                  clk_hps_ref.clk
		.gmm_fg_visor_sw_extern                     (<connected-to-gmm_fg_visor_sw_extern>),                     //              gmm_fg_visor_sw.extern
		.hps_0_hps_io_hps_io_sdio_inst_CMD          (<connected-to-hps_0_hps_io_hps_io_sdio_inst_CMD>),          //                 hps_0_hps_io.hps_io_sdio_inst_CMD
		.hps_0_hps_io_hps_io_sdio_inst_D0           (<connected-to-hps_0_hps_io_hps_io_sdio_inst_D0>),           //                             .hps_io_sdio_inst_D0
		.hps_0_hps_io_hps_io_sdio_inst_D1           (<connected-to-hps_0_hps_io_hps_io_sdio_inst_D1>),           //                             .hps_io_sdio_inst_D1
		.hps_0_hps_io_hps_io_sdio_inst_CLK          (<connected-to-hps_0_hps_io_hps_io_sdio_inst_CLK>),          //                             .hps_io_sdio_inst_CLK
		.hps_0_hps_io_hps_io_sdio_inst_D2           (<connected-to-hps_0_hps_io_hps_io_sdio_inst_D2>),           //                             .hps_io_sdio_inst_D2
		.hps_0_hps_io_hps_io_sdio_inst_D3           (<connected-to-hps_0_hps_io_hps_io_sdio_inst_D3>),           //                             .hps_io_sdio_inst_D3
		.hps_0_hps_io_hps_io_uart0_inst_RX          (<connected-to-hps_0_hps_io_hps_io_uart0_inst_RX>),          //                             .hps_io_uart0_inst_RX
		.hps_0_hps_io_hps_io_uart0_inst_TX          (<connected-to-hps_0_hps_io_hps_io_uart0_inst_TX>),          //                             .hps_io_uart0_inst_TX
		.hps_0_hps_io_hps_io_gpio_inst_GPIO53       (<connected-to-hps_0_hps_io_hps_io_gpio_inst_GPIO53>),       //                             .hps_io_gpio_inst_GPIO53
		.memory_mem_a                               (<connected-to-memory_mem_a>),                               //                       memory.mem_a
		.memory_mem_ba                              (<connected-to-memory_mem_ba>),                              //                             .mem_ba
		.memory_mem_ck                              (<connected-to-memory_mem_ck>),                              //                             .mem_ck
		.memory_mem_ck_n                            (<connected-to-memory_mem_ck_n>),                            //                             .mem_ck_n
		.memory_mem_cke                             (<connected-to-memory_mem_cke>),                             //                             .mem_cke
		.memory_mem_cs_n                            (<connected-to-memory_mem_cs_n>),                            //                             .mem_cs_n
		.memory_mem_ras_n                           (<connected-to-memory_mem_ras_n>),                           //                             .mem_ras_n
		.memory_mem_cas_n                           (<connected-to-memory_mem_cas_n>),                           //                             .mem_cas_n
		.memory_mem_we_n                            (<connected-to-memory_mem_we_n>),                            //                             .mem_we_n
		.memory_mem_reset_n                         (<connected-to-memory_mem_reset_n>),                         //                             .mem_reset_n
		.memory_mem_dq                              (<connected-to-memory_mem_dq>),                              //                             .mem_dq
		.memory_mem_dqs                             (<connected-to-memory_mem_dqs>),                             //                             .mem_dqs
		.memory_mem_dqs_n                           (<connected-to-memory_mem_dqs_n>),                           //                             .mem_dqs_n
		.memory_mem_odt                             (<connected-to-memory_mem_odt>),                             //                             .mem_odt
		.memory_mem_dm                              (<connected-to-memory_mem_dm>),                              //                             .mem_dm
		.memory_oct_rzqin                           (<connected-to-memory_oct_rzqin>),                           //                             .oct_rzqin
		.reset_reset_n                              (<connected-to-reset_reset_n>),                              //                        reset.reset_n
		.terasic_camera_0_conduit_end_camera_d      (<connected-to-terasic_camera_0_conduit_end_camera_d>),      // terasic_camera_0_conduit_end.camera_d
		.terasic_camera_0_conduit_end_camera_fval   (<connected-to-terasic_camera_0_conduit_end_camera_fval>),   //                             .camera_fval
		.terasic_camera_0_conduit_end_camera_lval   (<connected-to-terasic_camera_0_conduit_end_camera_lval>),   //                             .camera_lval
		.terasic_camera_0_conduit_end_camera_pixclk (<connected-to-terasic_camera_0_conduit_end_camera_pixclk>)  //                             .camera_pixclk
	);

